// Prompts a LAWYER can hand the Advisor — shown under an empty chat's
// greeting, a different handful each time the tab is entered (`pickPrompts`).
// Each is written as the message itself (a click sends it), and leans on what
// the Advisor can see: the project's files, data collections, chat, timeline.

export const LAWYER_PROMPTS = [
  'Summarise this case in five bullet points, citing the file each point comes from',
  'Build a timeline of the key events in this case from the project’s files',
  'List every party in this project with their CNP / CUI, address and role',
  'Which deadlines and limitation periods follow from the documents in this project?',
  'Find contradictions between the documents in this project',
  'What evidence supports our position, and what is still missing?',
  'Draft a formal notice (somație de plată) to the debtor in this case',
  'Draft a reply to the latest letter received in this case',
  'Review the contract in this project and list the clauses that are risky for our client',
  'Which laws and articles apply to this case? Cite them exactly',
  'Check every law cited in the project’s documents — is any of it repealed or amended?',
  'Prepare a list of questions to ask the client at our next meeting',
  'Write a short, plain-language update for the client on where the case stands',
  'What are the strongest arguments the other side could make?',
  'Estimate the claim’s value from the documents, showing the calculation',
  'Draft a statement of claim (cerere de chemare în judecată) based on these facts',
  'Which documents still need to be translated, legalised or apostilled?',
  'Compare the two most recent versions of the contract and list what changed',
  'Extract every amount, due date and penalty from the project’s contracts',
  'Is the company in this case active at ANAF? Check its CUI and fiscal status',
  'List the court files connected to the parties in this project',
  'Draft an NDA between the parties in this project',
  'Draft a power of attorney (împuternicire) for our client to sign',
  'What does the CAEN code of the company in this case allow it to do?',
  'Turn the facts of this case into a chronological statement of facts for the court',
  'Which clauses of the contract could be void or abusive under Romanian law?',
  'Prepare a checklist of everything we need before filing in court',
  'Summarise the team chat about this case — decisions taken and open questions',
  'Write an email to the opposing counsel proposing a settlement meeting',
  'Identify the personal data in this project and how GDPR applies to it',
  'Which of the parties’ ID documents expire soon or are missing?',
  'Draft the minutes (proces-verbal) of the last meeting with the client',
  'Explain the procedure and the steps ahead in this case, with typical durations',
  'Which witnesses or experts could support our case, based on the files?',
  'List the obligations each party has under the contract and whether they were met',
  'Find every mention of a payment in the project and reconcile the totals',
  'Draft a notice of termination of the contract, citing the right clause',
  'What would a judge most likely rule, and on what grounds?',
  'Prepare a one-page brief of this case for a colleague taking it over',
  'Which documents in this project have not been read or scanned yet?',
  'Which of our client’s obligations fall due in the next 30 days?',
  'Is the claim in this case time-barred? Show when the limitation period started and ends',
  'List every procedural deadline we must meet in this case, with the legal basis',
  'What happens if we miss the next deadline, and can it be recovered?',
  'What are the weakest points of our own case, honestly?',
  'How would the other side attack our evidence?',
  'Which facts are disputed and which are common ground between the parties?',
  'What counter-claims could the other side bring?',
  'Rebut the other side’s main argument, point by point',
  'Which documents need a certified translation before we can use them in court?',
  'Which documents must be notarised before signing?',
  'Which of the parties’ documents are foreign, and what formalities apply to them?',
  'Build a timeline of every payment made and missed in this case',
  'Build a timeline of the correspondence between the parties',
  'When did each party first learn of the key facts? Cite the documents',
  'What is the realistic range of damages a court could award here?',
  'How have Romanian courts decided similar cases? Summarise the usual reasoning',
  'Should we settle or go to court? Weigh the options for the client',
  'Draft a settlement agreement (tranzacție) that ends this dispute',
  'Draft a mediation proposal to the other side',
  'Draft an appeal (apel) against the first-instance decision, based on its reasoning',
  'Draft a request for evidence (cerere de probatorii) for this case',
  'Draft a statement of defence (întâmpinare) to the claim in this project',
  'Draft a request for a precautionary seizure (sechestru asigurător)',
  'Draft a payment order request (ordonanță de plată) for the unpaid invoices',
  'Draft an enforcement request (cerere de executare silită) for the judgment',
  'Draft a complaint to ANPC on behalf of our client',
  'Draft a GDPR data-subject access request for our client',
  'Draft a lease agreement (contract de închiriere) between the parties in this project',
  'Draft a sale-purchase agreement for the property in this case',
  'Draft a service agreement between the two companies in this project',
  'Draft an employment contract for the person in this project',
  'Draft a loan agreement (contract de împrumut) with a repayment schedule',
  'Draft a shareholders’ decision (hotărâre AGA) for the company in this case',
  'Draft a declaration on own responsibility (declarație pe proprie răspundere) for the client',
  'Draft a mandate agreement (contract de mandat) between our firm and the client',
  'Draft a letter to the client explaining the costs and fees ahead',
  'Rewrite the last draft in plainer language for the client',
  'Make the last draft more formal and legally precise',
  'Shorten the contract in this project without changing its effect',
  'Translate the key clauses of the contract into English',
  'Which clauses are missing from the contract in this project?',
  'Is there a jurisdiction and applicable-law clause? Is it valid?',
  'Does the contract have a penalty clause, and is it enforceable?',
  'Does the contract allow termination for convenience? On what notice?',
  'Who bears the risk under the contract if the goods are lost?',
  'Is there a confidentiality obligation, and how long does it last?',
  'Which guarantees does the contract give our client?',
  'What force-majeure protection does the contract give each party?',
  'Is the contract signed and dated correctly by people with the power to sign?',
  'Who can legally sign for the company in this case, and in what capacity?',
  'Check the company’s shareholders and administrators from the project’s documents',
  'Is the company in this case in insolvency? What does that change for us?',
  'Which assets of the debtor could be enforced against?',
  'What taxes or fees apply to this transaction?',
  'What stamp duty (taxă de timbru) will the court claim cost?',
  'Estimate our client’s total costs if the case goes to appeal',
  'Which court has jurisdiction over this dispute, and why?',
  'Which procedure applies here — ordinary, small claims, or payment order?',
  'List the documents we must attach to the claim',
  'Draft the list of exhibits (opis) for the court file',
  'Summarise every hearing so far and what was decided',
  'Summarise the judgment in this project in plain language',
  'What are the grounds for appealing the judgment?',
  'Compare our client’s ID card details across all documents — do they match?',
  'Find every address used for the parties and flag the inconsistencies',
  'Which people appear in more than one document of this project?',
  'Map the relationships between the people and companies in this project',
  'What does the data collection on our client say, in short?',
  'Which facts in the data collections still need a source document?',
  'Which files in this project are duplicates or near-duplicates?',
  'Which pictures in this project show identity documents?',
  'What is said in the audio and video recordings of this project?',
  'Draft a letter asking the other side for the documents we are missing',
  'Draft a notice to the landlord or tenant under the lease in this project',
  'Draft a claim for unpaid wages based on the employment documents',
  'Draft a criminal complaint (plângere penală) based on the facts in this project',
  'Is there a criminal dimension to these facts? Which offences could apply?',
  'Which authorities should be notified in this case, and by when?',
  'What does the latest amendment of the applicable law change for this case?',
  'Explain the relevant Civil Code articles as they apply to our facts',
  'Explain the relevant Civil Procedure Code rules for our next step',
  'Prepare talking points for the next hearing',
  'Prepare a cross-examination plan for the other side’s witness',
  'Draft the closing arguments (concluzii scrise) for this case',
  'Prepare an internal memo on the legal risks of this matter',
  'List everything the client promised to send us and has not sent yet',
  'What should the next three steps in this case be, and who does them?',
  'Draft a task list for the team for this week on this case',
  'Write a status report for the partner in charge of this matter',
  'Check the numbering, defined terms and cross-references in the last draft',
  'Which blanks are still empty in the drafts of this project?',
  'Fill the contract’s blanks with the parties’ data from the data collections',
];

// An ENDLESS feed: batch after batch, each a fresh shuffle of the whole pool,
// never starting with what the last batch ended on.
export function nextPrompts(prev = [], n = 18) {
  const out = [];
  let last = prev[prev.length - 1];
  while (out.length < n) {
    const batch = pickPrompts(LAWYER_PROMPTS.length);
    if (batch[0] === last) batch.push(batch.shift());
    for (const p of batch) { if (out.length >= n) break; out.push(p); last = p; }
  }
  return out;
}

// A different handful each time: `n` distinct prompts, drawn at random.
export function pickPrompts(n = 5) {
  const pool = [...LAWYER_PROMPTS];
  for (let i = pool.length - 1; i > 0; i -= 1) {
    const j = Math.floor(Math.random() * (i + 1));
    [pool[i], pool[j]] = [pool[j], pool[i]];
  }
  return pool.slice(0, n);
}
