// Document templates — what a blank document can be turned into.
//
// A new, empty file opens on a chooser rather than on an empty preview and an
// advisor waiting for a prompt: "what do you want to make?", answered by
// picking one of these or describing something else.
//
// The point of a template is NOT that it saves typing — it is that the skeleton
// travels with the app instead of through the model. The outline below is
// client-side and costs nothing; the model is handed a structure to fill rather
// than asked to invent one, so the drafting turn is shorter, cheaper and comes
// back in a predictable shape every time. Adding a template is adding an entry
// to this array — no other file changes.

// The groups the chooser filters by, in the order its chips appear. `top` is
// not a group of its own: it is a flag on the templates a practice reaches for
// most, whatever they belong to.
export const TEMPLATE_CATEGORIES = [
  { id: 'top', label: 'Frecvente' },
  { id: 'cabinet', label: 'Cabinet' },
  { id: 'litigii', label: 'Litigii' },
  { id: 'contracte', label: 'Contracte' },
  { id: 'munca', label: 'Muncă' },
  { id: 'corporate', label: 'Corporate' },
  { id: 'gdpr', label: 'Compliance și GDPR' },
  { id: 'imobiliare', label: 'Imobiliare' },
];

// Skeletons. Documents of one family share most of their spine — every contract
// names its parties and ends on signatures, every pleading opens on the court
// and closes on evidence — so a template states only what is its own, in the
// middle, and the family supplies the rest.
const contract = (...mid) => [
  'Părțile contractante',
  'Obiectul contractului',
  ...mid,
  'Răspunderea contractuală',
  'Forța majoră',
  'Încetarea contractului',
  'Legea aplicabilă și soluționarea litigiilor',
  'Dispoziții finale',
  'Semnături',
];
const pleading = (...mid) => [
  'Instanța, dosarul și părțile',
  ...mid,
  'Temeiul de drept',
  'Probe',
  'Cheltuieli de judecată',
  'Anexe',
  'Data și semnătura',
];
const decision = (...mid) => [
  'Antet, număr și dată',
  'Preambul și temei legal',
  ...mid,
  'Comunicare și intrare în vigoare',
  'Semnături',
];
const policy = (...mid) => [
  'Scop și domeniu de aplicare',
  'Definiții',
  ...mid,
  'Responsabilități',
  'Revizuire și intrare în vigoare',
];

// Drafting rules a few documents share.
const NOTE_AUTHENTIC = 'Actul se încheie în formă autentică; redactează-l ca proiect pentru notarul public.';
const NOTE_ART_252 = 'Include toate mențiunile obligatorii prevăzute de art. 252 alin. (2) din Codul muncii, sub sancțiunea nulității absolute.';

// One entry. `opts.top` marks a most-used template; `opts.note` is an extra
// drafting rule for the few documents that have one (a mandatory form, a
// statute the text has to follow).
const t = (id, category, label, blurb, outline, opts = {}) => ({
  id, category, label, blurb, kind: 'docx', outline, ...opts,
});

export const DOC_TEMPLATES = [
  // ── Cabinet ───────────────────────────────────────────────────────────
  t('asistenta-juridica', 'cabinet', 'Contract de asistență juridică', 'Se încheie cu fiecare client nou — formular UNBR.', [
    'Forma de exercitare a profesiei și clientul',
    'Obiectul contractului',
    'Onorariul',
    'Cheltuieli în interesul clientului',
    'Drepturile și obligațiile avocatului',
    'Drepturile și obligațiile clientului',
    'Confidențialitate și protecția datelor',
    'Durata și încetarea contractului',
    'Clauze speciale',
    'Semnături',
  ], { top: true, note: 'Respectă structura formularului de contract de asistență juridică din Statutul profesiei de avocat (UNBR), inclusiv numărul și data înregistrării în registrul oficial de evidență.' }),
  t('imputernicire-avocatiala', 'cabinet', 'Împuternicire avocațială', 'Dovada mandatului în fața instanțelor și autorităților — formular UNBR.', [
    'Baroul și forma de exercitare a profesiei',
    'Seria și numărul împuternicirii',
    'Avocatul împuternicit',
    'Clientul și contractul de asistență juridică',
    'Activitățile pentru care se acordă împuternicirea',
    'Autoritatea în fața căreia se exercită',
    'Data, semnături și ștampilă',
  ], { top: true, note: 'Respectă formularul de împuternicire avocațială din Statutul profesiei de avocat (UNBR). Documentul are o singură pagină.' }),
  t('opinie-juridica', 'cabinet', 'Opinie juridică', 'Consultație scrisă sau memo pentru client.', [
    'Destinatar, dată și obiectul consultației',
    'Situația de fapt avută în vedere',
    'Documente analizate',
    'Întrebările adresate',
    'Cadrul legal aplicabil',
    'Analiză',
    'Riscuri identificate',
    'Concluzii și recomandări',
    'Limitele opiniei',
  ], { top: true }),

  // ── Litigii ───────────────────────────────────────────────────────────
  t('chemare-judecata', 'litigii', 'Cerere de chemare în judecată', 'Cererea introductivă, în forma cerută de art. 194 C. proc. civ.', pleading(
    'Obiectul cererii și valoarea lui',
    'Situația de fapt',
    'Motivele de drept',
    'Solicitări',
  ), { top: true }),
  t('intampinare', 'litigii', 'Întâmpinare', 'Răspunsul pârâtului la cererea de chemare în judecată.', pleading(
    'Excepții procesuale',
    'Răspunsul la pretențiile reclamantului',
    'Situația de fapt',
    'Apărări în drept',
    'Solicitări',
  ), { top: true }),
  t('reconventionala', 'litigii', 'Cerere reconvențională', 'Pretențiile pârâtului împotriva reclamantului, în același dosar.', pleading(
    'Legătura cu cererea principală',
    'Obiectul cererii și valoarea lui',
    'Situația de fapt',
    'Motivele de drept',
    'Solicitări',
  )),
  t('raspuns-intampinare', 'litigii', 'Răspuns la întâmpinare', 'Replica reclamantului la apărările pârâtului.', pleading(
    'Răspuns la excepțiile invocate',
    'Răspuns la apărările de fond',
    'Precizări asupra situației de fapt',
    'Solicitări',
  )),
  t('notificare', 'litigii', 'Notificare / punere în întârziere', 'Somație adresată debitorului înainte de sesizarea instanței.', [
    'Expeditor și destinatar',
    'Raportul juridic dintre părți',
    'Obligația neexecutată',
    'Suma datorată și modul de calcul',
    'Termenul acordat pentru conformare',
    'Consecințele neconformării',
    'Modalitatea de plată',
    'Data și semnătura',
  ], { top: true }),
  t('concluzii-scrise', 'litigii', 'Concluzii scrise', 'Sinteza susținerilor la închiderea dezbaterilor.', pleading(
    'Obiectul cauzei',
    'Starea de fapt rezultată din probe',
    'Analiza probelor administrate',
    'Argumente în drept',
    'Răspuns la susținerile părții adverse',
    'Solicitări',
  ), { top: true }),
  t('note-sedinta', 'litigii', 'Note de ședință', 'Precizări scurte depuse pentru un termen de judecată.', pleading(
    'Termenul pentru care se depun',
    'Aspectele puse în discuție',
    'Poziția părții',
    'Solicitări',
  ), { top: true }),
  t('ordonanta-plata', 'litigii', 'Cerere de ordonanță de plată', 'Recuperarea creanțelor certe, lichide și exigibile (art. 1014 C. proc. civ.).', pleading(
    'Creanța: izvor, cuantum și scadență',
    'Dovada somației prealabile',
    'Caracterul cert, lichid și exigibil al creanței',
    'Dobânzi și penalități',
    'Solicitări',
  )),
  t('valoare-redusa', 'litigii', 'Cerere de valoare redusă', 'Procedura simplificată pentru pretenții de valoare mică.', pleading(
    'Valoarea cererii și admisibilitatea procedurii',
    'Pretenția și temeiul ei',
    'Situația de fapt',
    'Solicitarea privind dezbaterile orale',
    'Solicitări',
  ), { note: 'Urmează rubricile formularului de cerere aprobat prin ordin al ministrului justiției pentru procedura cererilor de valoare redusă.' }),
  t('ordonanta-presedintiala', 'litigii', 'Cerere de ordonanță președințială', 'Măsuri provizorii în cazuri urgente.', pleading(
    'Măsura solicitată',
    'Situația de fapt',
    'Aparența dreptului',
    'Urgența',
    'Caracterul provizoriu și neprejudecarea fondului',
    'Solicitări',
  )),
  t('sechestru-asigurator', 'litigii', 'Cerere de sechestru asigurător', 'Indisponibilizarea bunurilor debitorului până la soluționarea fondului.', pleading(
    'Creanța și acțiunea de fond introdusă',
    'Bunurile asupra cărora se cere sechestrul',
    'Condițiile de admisibilitate',
    'Cauțiunea',
    'Solicitări',
  )),
  t('poprire-asiguratorie', 'litigii', 'Cerere de poprire asigurătorie', 'Indisponibilizarea sumelor datorate debitorului de terți.', pleading(
    'Creanța și acțiunea de fond introdusă',
    'Terții popriți și sumele vizate',
    'Condițiile de admisibilitate',
    'Cauțiunea',
    'Solicitări',
  )),
  t('contestatie-executare', 'litigii', 'Contestație la executare', 'Împotriva executării silite sau a unui act de executare.', pleading(
    'Dosarul de executare și actele contestate',
    'Termenul de formulare',
    'Situația de fapt',
    'Motivele de nelegalitate',
    'Cererea de suspendare a executării',
    'Solicitări',
  )),
  t('suspendare-executare', 'litigii', 'Cerere de suspendare a executării', 'Oprirea executării silite până la soluționarea contestației.', pleading(
    'Dosarul de executare și contestația formulată',
    'Motivele temeinice ale suspendării',
    'Prejudiciul iminent',
    'Cauțiunea',
    'Solicitări',
  )),
  t('executare-silita', 'litigii', 'Cerere de executare silită', 'Sesizarea executorului judecătoresc cu punerea în executare a titlului.', [
    'Executorul judecătoresc sesizat',
    'Creditorul și debitorul',
    'Titlul executoriu',
    'Creanța de executat și accesoriile',
    'Modalitățile de executare solicitate',
    'Bunurile și veniturile cunoscute ale debitorului',
    'Anexe',
    'Data și semnătura',
  ]),
  t('apel', 'litigii', 'Cerere de apel și motive de apel', 'Calea de atac împotriva hotărârii primei instanțe.', pleading(
    'Hotărârea atacată',
    'Termenul de declarare a apelului',
    'Situația de fapt reținută de prima instanță',
    'Motivele de apel',
    'Probe noi în apel',
    'Solicitări',
  ), { top: true }),
  t('recurs', 'litigii', 'Cerere de recurs', 'Cale extraordinară de atac, pentru motive de nelegalitate (art. 488 C. proc. civ.).', pleading(
    'Hotărârea atacată',
    'Admisibilitatea și termenul recursului',
    'Motivele de casare',
    'Dezvoltarea motivelor de nelegalitate',
    'Solicitări',
  )),
  t('contestatie-anulare', 'litigii', 'Contestație în anulare', 'Retractarea unei hotărâri definitive pentru vicii procedurale.', pleading(
    'Hotărârea atacată',
    'Admisibilitatea și termenul',
    'Motivul de contestație invocat',
    'Dezvoltarea motivului',
    'Solicitări',
  )),
  t('revizuire', 'litigii', 'Cerere de revizuire', 'Retractarea unei hotărâri pentru motivele din art. 509 C. proc. civ.', pleading(
    'Hotărârea a cărei revizuire se cere',
    'Motivul de revizuire și termenul',
    'Împrejurările noi',
    'Dezvoltarea motivului',
    'Solicitări',
  )),
  t('plangere-contraventionala', 'litigii', 'Plângere contravențională', 'Împotriva procesului-verbal de contravenție (OG 2/2001).', pleading(
    'Procesul-verbal contestat',
    'Termenul de formulare a plângerii',
    'Situația de fapt',
    'Motive de nulitate a procesului-verbal',
    'Motive de netemeinicie',
    'Individualizarea sancțiunii',
    'Solicitări',
  )),
  t('plangere-penala', 'litigii', 'Plângere penală', 'Sesizarea organelor de urmărire penală de către persoana vătămată.', [
    'Organul de urmărire penală sesizat',
    'Persoana vătămată',
    'Făptuitorul, dacă este cunoscut',
    'Descrierea faptei',
    'Încadrarea juridică',
    'Prejudiciul și constituirea ca parte civilă',
    'Mijloace de probă',
    'Anexe',
    'Data și semnătura',
  ]),
  t('denunt', 'litigii', 'Denunț', 'Încunoștințarea organelor penale despre săvârșirea unei infracțiuni.', [
    'Organul de urmărire penală sesizat',
    'Denunțătorul',
    'Descrierea faptei',
    'Persoanele implicate',
    'Încadrarea juridică',
    'Mijloace de probă',
    'Data și semnătura',
  ]),
  t('plangere-solutie-procuror', 'litigii', 'Plângere împotriva soluției procurorului', 'Împotriva clasării sau renunțării la urmărirea penală (art. 339–340 C. proc. pen.).', [
    'Organul sesizat și dosarul penal',
    'Petentul și calitatea sa',
    'Soluția atacată și comunicarea ei',
    'Termenul de formulare',
    'Situația de fapt',
    'Critici aduse soluției',
    'Probe neadministrate sau greșit apreciate',
    'Solicitări',
    'Data și semnătura',
  ]),
  t('cerere-probe', 'litigii', 'Cerere de încuviințare a probelor', 'Propunerea probelor și teza probatorie a fiecăreia.', pleading(
    'Probele propuse',
    'Teza probatorie a fiecărei probe',
    'Utilitatea și pertinența probelor',
    'Martorii propuși',
    'Solicitări',
  )),
  t('interogatoriu', 'litigii', 'Interogatoriu', 'Întrebările propuse părții adverse.', [
    'Instanța, dosarul și părțile',
    'Partea chemată la interogatoriu',
    'Întrebări privind raportul juridic',
    'Întrebări privind executarea obligațiilor',
    'Întrebări privind prejudiciul',
    'Data și semnătura',
  ], { note: 'Formulează întrebările numerotate, scurte, la persoana a II-a, fiecare privind un singur fapt personal al părții.' }),
  t('cerere-expertiza', 'litigii', 'Cerere de expertiză', 'Încuviințarea unei expertize și obiectivele ei.', pleading(
    'Specialitatea expertizei',
    'Necesitatea probei',
    'Obiectivele propuse',
    'Expertul consilier al părții',
    'Solicitări',
  )),
  t('cerere-amanare', 'litigii', 'Cerere de amânare', 'Amânarea judecății pentru un motiv temeinic.', [
    'Instanța, dosarul și părțile',
    'Termenul vizat',
    'Motivul amânării',
    'Dovezi',
    'Solicitări',
    'Data și semnătura',
  ]),
  t('repunere-rol', 'litigii', 'Cerere de repunere pe rol', 'Reluarea judecății după suspendare.', [
    'Instanța, dosarul și părțile',
    'Măsura suspendării și temeiul ei',
    'Încetarea cauzei de suspendare',
    'Taxa judiciară de timbru',
    'Solicitări',
    'Data și semnătura',
  ]),
  t('actiune-pretentii', 'litigii', 'Acțiune în pretenții', 'Obligarea pârâtului la plata unei sume de bani.', pleading(
    'Obiectul cererii și valoarea lui',
    'Raportul juridic dintre părți',
    'Neexecutarea obligației de plată',
    'Debitul principal, dobânzi și penalități',
    'Motivele de drept',
    'Solicitări',
  )),
  t('actiune-anulare-act', 'litigii', 'Acțiune în anularea unui act', 'Constatarea nulității absolute sau anularea unui act juridic.', pleading(
    'Actul atacat',
    'Calitatea procesuală și interesul',
    'Situația de fapt',
    'Cauza de nulitate',
    'Efectele nulității și repunerea în situația anterioară',
    'Solicitări',
  )),
  t('actiune-revendicare', 'litigii', 'Acțiune în revendicare', 'Recunoașterea dreptului de proprietate și restituirea bunului.', pleading(
    'Bunul revendicat și valoarea lui',
    'Titlul de proprietate al reclamantului',
    'Posesia exercitată de pârât',
    'Compararea titlurilor',
    'Solicitări',
  )),
  t('actiune-partaj', 'litigii', 'Acțiune de partaj', 'Ieșirea din indiviziune asupra bunurilor comune.', pleading(
    'Coproprietarii și cotele lor',
    'Titlul care stă la baza coproprietății',
    'Masa partajabilă',
    'Datoriile și creanțele dintre coproprietari',
    'Modalitatea de partaj propusă',
    'Solicitări',
  )),
  t('actiune-evacuare', 'litigii', 'Cerere de evacuare', 'Evacuarea din imobilul folosit fără drept (art. 1034 și urm. C. proc. civ.).', pleading(
    'Imobilul și titlul reclamantului',
    'Raportul de locațiune sau lipsa titlului',
    'Notificarea prealabilă',
    'Situația de fapt',
    'Solicitări',
  )),
  t('actiune-divort', 'litigii', 'Cerere de divorț', 'Desfacerea căsătoriei și cererile accesorii.', pleading(
    'Căsătoria și ultima locuință comună',
    'Copiii minori',
    'Motivele de divorț',
    'Numele după divorț',
    'Autoritatea părintească și locuința minorului',
    'Contribuția la cheltuielile de creștere și educare',
    'Solicitări',
  )),
  t('pensie-intretinere', 'litigii', 'Pensie de întreținere și program de legături personale', 'Stabilirea sau modificarea pensiei și a programului de vizită.', pleading(
    'Părțile și minorul',
    'Situația actuală a minorului',
    'Veniturile părintelui debitor',
    'Cuantumul pensiei solicitate',
    'Programul de legături personale propus',
    'Interesul superior al minorului',
    'Solicitări',
  )),
  t('raspundere-delictuala', 'litigii', 'Acțiune în răspundere civilă delictuală', 'Repararea prejudiciului cauzat printr-o faptă ilicită.', pleading(
    'Obiectul cererii și valoarea lui',
    'Fapta ilicită',
    'Prejudiciul material și moral',
    'Legătura de cauzalitate',
    'Vinovăția',
    'Solicitări',
  )),

  // ── Contracte civile și comerciale ────────────────────────────────────
  {
    id: 'nda',
    category: 'contracte',
    label: 'Contract NDA',
    blurb: 'Acord de confidențialitate între două părți.',
    kind: 'docx',
    // The sections the finished document must have, in order. Sent verbatim,
    // so the model spends its budget on the CLAUSES, not on deciding what an
    // NDA contains.
    outline: [
      'Părțile contractante',
      'Obiectul contractului',
      'Definiția informațiilor confidențiale',
      'Obligațiile părții care primește informațiile',
      'Excepții de la confidențialitate',
      'Durata obligației de confidențialitate',
      'Răspunderea contractuală și penalități',
      'Legea aplicabilă și soluționarea litigiilor',
      'Semnături',
    ],
  },
  {
    id: 'sale',
    category: 'contracte',
    label: 'Contract vânzare-cumpărare',
    blurb: 'Transferul proprietății unui bun de la vânzător la cumpărător.',
    kind: 'docx',
    outline: [
      'Părțile contractante',
      'Obiectul contractului și identificarea bunului',
      'Prețul și modalitatea de plată',
      'Predarea bunului și transferul proprietății',
      'Garanții privind bunul vândut',
      'Obligațiile vânzătorului',
      'Obligațiile cumpărătorului',
      'Răspunderea contractuală',
      'Legea aplicabilă și soluționarea litigiilor',
      'Semnături',
    ],
  },
  t('prestari-servicii', 'contracte', 'Contract de prestări servicii', 'Cel mai reutilizat șablon: servicii contra unui preț.', contract(
    'Descrierea serviciilor',
    'Durata contractului',
    'Prețul și modalitatea de plată',
    'Obligațiile prestatorului',
    'Obligațiile beneficiarului',
    'Recepția serviciilor',
    'Confidențialitate',
  ), { top: true }),
  t('act-aditional', 'contracte', 'Act adițional la contract', 'Modifică sau completează un contract existent.', [
    'Părțile și contractul modificat',
    'Preambul',
    'Clauzele modificate',
    'Clauzele nou introduse',
    'Clauzele eliminate',
    'Menținerea celorlalte prevederi',
    'Intrarea în vigoare',
    'Semnături',
  ], { top: true }),
  t('antecontract', 'contracte', 'Antecontract / promisiune bilaterală de vânzare', 'Părțile se obligă să încheie în viitor contractul de vânzare.', contract(
    'Bunul promis spre vânzare',
    'Prețul, avansul și modalitatea de plată',
    'Termenul de încheiere a contractului',
    'Obligațiile promitentului-vânzător',
    'Obligațiile promitentului-cumpărător',
    'Clauza penală și pactul comisoriu',
  )),
  t('inchiriere', 'contracte', 'Contract de închiriere (locațiune)', 'Folosința unui bun contra unei chirii.', contract(
    'Bunul închiriat și destinația lui',
    'Durata locațiunii',
    'Chiria și modalitatea de plată',
    'Garanția',
    'Utilități și cheltuieli de întreținere',
    'Obligațiile locatorului',
    'Obligațiile locatarului',
    'Predarea și restituirea bunului',
  )),
  t('comodat', 'contracte', 'Contract de comodat', 'Împrumut de folosință cu titlu gratuit.', contract(
    'Bunul dat în folosință',
    'Durata comodatului',
    'Obligațiile comodantului',
    'Obligațiile comodatarului',
    'Restituirea bunului',
  )),
  t('antrepriza', 'contracte', 'Contract de antrepriză', 'Executarea unei lucrări pe riscul antreprenorului.', contract(
    'Lucrarea și specificațiile tehnice',
    'Termenele de execuție',
    'Prețul și modalitatea de plată',
    'Materiale și subantrepriză',
    'Obligațiile antreprenorului',
    'Obligațiile beneficiarului',
    'Recepția lucrării și garanția',
    'Penalități de întârziere',
  )),
  t('furnizare', 'contracte', 'Contract de furnizare', 'Livrări succesive de bunuri sau servicii.', contract(
    'Produsele și specificațiile lor',
    'Comenzi, cantități și grafic de livrare',
    'Prețul și modalitatea de plată',
    'Livrarea și transferul riscurilor',
    'Calitate, recepție și reclamații',
    'Garanția produselor',
    'Penalități',
  )),
  t('mandat', 'contracte', 'Contract de mandat', 'Încheierea de acte juridice pe seama mandantului.', contract(
    'Întinderea mandatului',
    'Durata mandatului',
    'Remunerația mandatarului',
    'Obligațiile mandatarului',
    'Obligațiile mandantului',
    'Substituirea mandatarului',
    'Revocarea și renunțarea',
  )),
  t('agentie', 'contracte', 'Contract de agenție', 'Agentul negociază sau încheie contracte pentru comitent, în mod statornic.', contract(
    'Teritoriul și exclusivitatea',
    'Durata contractului',
    'Comisionul agentului',
    'Obligațiile agentului',
    'Obligațiile comitentului',
    'Clauza de neconcurență',
    'Indemnizația la încetare',
  )),
  t('comision', 'contracte', 'Contract de comision', 'Comisionarul contractează în nume propriu, pe seama comitentului.', contract(
    'Operațiunile încredințate',
    'Instrucțiunile comitentului',
    'Comisionul',
    'Obligațiile comisionarului',
    'Obligațiile comitentului',
    'Răspunderea pentru terți',
  )),
  t('intermediere', 'contracte', 'Contract de intermediere', 'Punerea în legătură a clientului cu un terț în vederea unui contract.', contract(
    'Activitatea de intermediere',
    'Durata și exclusivitatea',
    'Remunerația intermediarului',
    'Obligațiile intermediarului',
    'Obligațiile clientului',
    'Confidențialitate',
  )),
  t('imprumut', 'contracte', 'Contract de împrumut', 'Împrumut de consumație, cu sau fără dobândă.', contract(
    'Suma împrumutată și predarea ei',
    'Dobânda',
    'Termenul și modalitatea de restituire',
    'Garanții',
    'Rambursarea anticipată',
    'Exigibilitatea anticipată',
  )),
  t('cesiune-creanta', 'contracte', 'Contract de cesiune de creanță', 'Transmiterea unei creanțe către un terț.', contract(
    'Creanța cedată și izvorul ei',
    'Prețul cesiunii',
    'Garanția existenței creanței',
    'Predarea înscrisurilor',
    'Notificarea debitorului cedat',
    'Obligațiile părților',
  )),
  t('preluare-datorie', 'contracte', 'Contract de preluare de datorie', 'Un nou debitor preia obligația debitorului inițial.', contract(
    'Datoria preluată',
    'Acordul creditorului',
    'Efectele asupra debitorului inițial',
    'Soarta garanțiilor',
    'Obligațiile părților',
  )),
  t('fideiusiune', 'contracte', 'Contract de fideiusiune', 'Garanție personală pentru datoria altuia.', contract(
    'Obligația garantată',
    'Întinderea fideiusiunii',
    'Beneficiul de discuțiune și de diviziune',
    'Obligațiile fideiusorului',
    'Obligația de informare a creditorului',
    'Regresul împotriva debitorului',
  )),
  t('ipoteca-mobiliara', 'contracte', 'Contract de ipotecă mobiliară', 'Garanție reală asupra bunurilor mobile, înscrisă în RNPM.', contract(
    'Obligația garantată și suma maximă',
    'Bunurile ipotecate',
    'Declarații și garanții ale constituitorului',
    'Obligațiile constituitorului',
    'Înscrierea în Registrul Național de Publicitate Mobiliară',
    'Cazuri de culpă și executarea ipotecii',
  )),
  t('ipoteca-imobiliara', 'contracte', 'Contract de ipotecă imobiliară', 'Garanție reală asupra unui imobil — formă autentică.', contract(
    'Obligația garantată și suma maximă',
    'Imobilul ipotecat',
    'Declarații și garanții ale constituitorului',
    'Interdicții de înstrăinare și grevare',
    'Asigurarea imobilului',
    'Înscrierea în cartea funciară',
    'Cazuri de culpă și executarea ipotecii',
  ), { note: NOTE_AUTHENTIC }),
  t('memorandum-loi', 'contracte', 'Memorandum / scrisoare de intenție', 'Intenția părților de a negocia o tranzacție.', [
    'Părțile',
    'Tranzacția avută în vedere',
    'Principalii termeni comerciali',
    'Calendarul negocierilor și due diligence',
    'Exclusivitate',
    'Confidențialitate',
    'Costuri',
    'Caracterul obligatoriu sau neobligatoriu al prevederilor',
    'Legea aplicabilă',
    'Semnături',
  ]),
  t('term-sheet', 'contracte', 'Term sheet', 'Termenii principali ai unei investiții sau tranzacții.', [
    'Părțile și tranzacția',
    'Evaluare și structura investiției',
    'Prețul și mecanismul de plată',
    'Condiții precedente',
    'Declarații și garanții',
    'Guvernanță și drepturi ale investitorului',
    'Exclusivitate și confidențialitate',
    'Prevederi obligatorii și neobligatorii',
    'Semnături',
  ]),
  t('cesiune-drepturi-autor', 'contracte', 'Contract de cesiune a drepturilor de autor', 'Transmiterea drepturilor patrimoniale asupra unei opere (Legea 8/1996).', contract(
    'Opera',
    'Drepturile patrimoniale cesionate',
    'Caracterul exclusiv sau neexclusiv',
    'Teritoriul și durata cesiunii',
    'Remunerația',
    'Drepturile morale ale autorului',
    'Garanția de originalitate',
  )),
  t('licenta', 'contracte', 'Contract de licență', 'Dreptul de utilizare a unui software, a unei mărci sau a unui brevet.', contract(
    'Obiectul licenței',
    'Întinderea, teritoriul și exclusivitatea',
    'Durata licenței',
    'Redevența',
    'Restricții de utilizare',
    'Mentenanță și actualizări',
    'Proprietate intelectuală și garanții',
  )),
  t('dezvoltare-software', 'contracte', 'Contract de dezvoltare software', 'Dezvoltarea unei aplicații la comandă.', contract(
    'Specificații și livrabile',
    'Etape, termene și metodologie',
    'Prețul și modalitatea de plată',
    'Testare și acceptanță',
    'Proprietatea intelectuală și codul-sursă',
    'Garanție, mentenanță și suport',
    'Confidențialitate și protecția datelor',
    'Limitarea răspunderii',
  )),
  t('franciza', 'contracte', 'Contract de franciză', 'Exploatarea unui concept de afaceri sub marca francizorului (OG 52/1997).', contract(
    'Conceptul, marca și know-how-ul',
    'Teritoriul și exclusivitatea',
    'Durata contractului',
    'Taxa de intrare și redevențele',
    'Obligațiile francizorului',
    'Obligațiile beneficiarului',
    'Standarde, control și formare',
    'Neconcurență și confidențialitate',
  )),
  t('distributie', 'contracte', 'Contract de distribuție', 'Revânzarea produselor furnizorului pe un teritoriu.', contract(
    'Produsele și teritoriul',
    'Exclusivitatea',
    'Durata contractului',
    'Prețuri, comenzi și condiții de plată',
    'Ținte minime de achiziție',
    'Obligațiile furnizorului',
    'Obligațiile distribuitorului',
    'Marca și materialele promoționale',
  )),
  t('leasing', 'contracte', 'Contract de leasing', 'Folosința unui bun cu opțiune de cumpărare la final (OG 51/1997).', contract(
    'Bunul și furnizorul',
    'Durata leasingului',
    'Valoarea de intrare, ratele și valoarea reziduală',
    'Predarea bunului',
    'Asigurarea bunului',
    'Obligațiile finanțatorului',
    'Obligațiile utilizatorului',
    'Opțiunea de cumpărare',
  )),
  t('acord-incetare', 'contracte', 'Acord de încetare a contractului', 'Încetarea unui contract prin acordul părților.', [
    'Părțile și contractul care încetează',
    'Data încetării',
    'Obligații scadente și decontul final',
    'Restituirea bunurilor și a documentelor',
    'Clauze care supraviețuiesc încetării',
    'Renunțarea reciprocă la pretenții',
    'Semnături',
  ]),
  t('tranzactie', 'contracte', 'Contract de tranzacție (settlement)', 'Stingerea unui litigiu prin concesii reciproce.', [
    'Părțile',
    'Litigiul dintre părți',
    'Concesiile reciproce',
    'Sumele datorate și termenele de plată',
    'Renunțarea la pretenții și la judecată',
    'Confidențialitate',
    'Clauza penală',
    'Legea aplicabilă',
    'Semnături',
  ]),
  t('notificare-reziliere', 'contracte', 'Notificare de reziliere', 'Declarația unilaterală de reziliere pentru neexecutare.', [
    'Expeditor și destinatar',
    'Contractul vizat',
    'Obligațiile neexecutate',
    'Punerea în întârziere anterioară',
    'Declarația de reziliere și data de la care produce efecte',
    'Sume datorate și daune-interese',
    'Restituirea prestațiilor',
    'Data și semnătura',
  ]),
  t('pv-predare-primire', 'contracte', 'Proces-verbal de predare-primire', 'Constată predarea unui bun sau a unor documente.', [
    'Părțile și contractul în temeiul căruia se face predarea',
    'Data și locul predării',
    'Bunurile predate',
    'Starea bunurilor și observații',
    'Documente și accesorii predate',
    'Semnături',
  ]),
  t('pv-receptie', 'contracte', 'Proces-verbal de recepție', 'Constată recepția lucrărilor sau a serviciilor.', [
    'Părțile și contractul',
    'Comisia de recepție',
    'Lucrările sau serviciile recepționate',
    'Constatări',
    'Neconformități și termene de remediere',
    'Concluzia recepției',
    'Semnături',
  ]),

  // ── Dreptul muncii ────────────────────────────────────────────────────
  t('cim', 'munca', 'Contract individual de muncă', 'Conform modelului-cadru aprobat de Ministerul Muncii.', [
    'Părțile contractului',
    'Obiectul contractului',
    'Durata contractului',
    'Locul de muncă',
    'Felul muncii',
    'Atribuțiile postului',
    'Durata muncii și repartizarea programului',
    'Concediul',
    'Salarizarea',
    'Drepturi și obligații ale părților',
    'Perioada de probă și preavizul',
    'Dispoziții finale',
    'Semnături',
  ], { note: 'Respectă rubricile modelului-cadru al contractului individual de muncă aprobat prin ordin al ministrului muncii și art. 17 din Codul muncii.' }),
  t('act-aditional-cim', 'munca', 'Act adițional la contractul de muncă', 'Modificare de salariu, funcție sau timp de lucru.', [
    'Părțile și contractul de muncă modificat',
    'Elementul modificat',
    'Noua formulare a clauzei',
    'Data de la care se aplică',
    'Menținerea celorlalte clauze',
    'Semnături',
  ]),
  t('fisa-postului', 'munca', 'Fișa postului', 'Atribuțiile, relațiile și cerințele unui post.', [
    'Denumirea postului și codul COR',
    'Poziția în organigramă și relații ierarhice',
    'Scopul postului',
    'Atribuții și responsabilități',
    'Cerințe de studii și experiență',
    'Competențe',
    'Criterii de evaluare a performanței',
    'Sănătate și securitate în muncă',
    'Semnături',
  ]),
  t('regulament-intern', 'munca', 'Regulament intern', 'Conținutul minim cerut de art. 242 din Codul muncii.', [
    'Dispoziții generale',
    'Protecția, igiena și securitatea în muncă',
    'Nediscriminare și respectarea demnității',
    'Drepturile și obligațiile angajatorului și ale salariaților',
    'Soluționarea cererilor și reclamațiilor salariaților',
    'Disciplina muncii',
    'Abateri disciplinare și sancțiuni',
    'Procedura disciplinară',
    'Evaluarea profesională a salariaților',
    'Informarea salariaților și preavizul',
    'Dispoziții finale',
  ]),
  t('rof', 'munca', 'Regulament de organizare și funcționare (ROF)', 'Structura organizatorică și atribuțiile compartimentelor.', [
    'Dispoziții generale',
    'Structura organizatorică',
    'Conducerea societății',
    'Atribuțiile compartimentelor',
    'Relații funcționale între compartimente',
    'Circuitul documentelor',
    'Dispoziții finale',
  ]),
  t('decizie-sanctionare', 'munca', 'Decizie de sancționare disciplinară', 'Cu elementele obligatorii din art. 252 Codul muncii.', decision(
    'Descrierea faptei care constituie abatere',
    'Prevederile încălcate',
    'Apărările salariatului și motivele înlăturării lor',
    'Sancțiunea aplicată și temeiul ei',
    'Termenul și instanța la care poate fi contestată',
  ), { note: NOTE_ART_252 }),
  t('decizie-concediere-disciplinara', 'munca', 'Decizie de concediere disciplinară', 'Concediere pentru abatere gravă sau abateri repetate (art. 61 lit. a).', decision(
    'Descrierea faptei care constituie abatere',
    'Prevederile încălcate',
    'Cercetarea disciplinară și apărările salariatului',
    'Încetarea contractului de muncă și data ei',
    'Termenul și instanța la care poate fi contestată',
  ), { note: NOTE_ART_252 }),
  t('decizie-concediere-economica', 'munca', 'Decizie de concediere pentru motive economice', 'Desființarea postului (art. 65 Codul muncii).', decision(
    'Motivele care determină concedierea',
    'Desființarea efectivă a postului',
    'Durata preavizului',
    'Criteriile de stabilire a ordinii de priorități',
    'Lista locurilor de muncă disponibile',
    'Termenul și instanța la care poate fi contestată',
  )),
  t('decizie-incetare-drept', 'munca', 'Decizie de constatare a încetării de drept', 'Încetarea contractului în cazurile din art. 56 Codul muncii.', decision(
    'Cazul de încetare de drept',
    'Data încetării contractului',
    'Drepturi salariale cuvenite',
  )),
  t('decizie-delegare', 'munca', 'Decizie de delegare', 'Exercitarea temporară a atribuțiilor în alt loc de muncă.', decision(
    'Salariatul delegat',
    'Locul și durata delegării',
    'Atribuțiile pe durata delegării',
    'Drepturi bănești: transport, cazare, indemnizație',
  )),
  t('decizie-detasare', 'munca', 'Decizie de detașare', 'Schimbarea temporară a locului de muncă la alt angajator.', decision(
    'Salariatul detașat',
    'Angajatorul la care se face detașarea',
    'Durata detașării',
    'Felul muncii și drepturile salariale',
    'Drepturi bănești: transport, cazare, indemnizație',
  )),
  t('decizie-suspendare', 'munca', 'Decizie de suspendare a contractului de muncă', 'Suspendare de drept, la inițiativa unei părți sau prin acord.', decision(
    'Cazul de suspendare',
    'Durata suspendării',
    'Efectele asupra drepturilor salariatului',
    'Reluarea activității',
  )),
  t('convocator-cercetare', 'munca', 'Convocator la cercetarea disciplinară', 'Convocarea scrisă cerută de art. 251 Codul muncii.', [
    'Angajatorul și salariatul convocat',
    'Obiectul cercetării: fapta imputată',
    'Data, ora și locul întrevederii',
    'Comisia de cercetare',
    'Drepturile salariatului',
    'Consecințele neprezentării',
    'Data și semnătura',
  ]),
  t('pv-cercetare', 'munca', 'Proces-verbal de cercetare disciplinară', 'Consemnează desfășurarea cercetării.', [
    'Comisia și salariatul cercetat',
    'Convocarea și prezența',
    'Fapta cercetată',
    'Declarațiile și apărările salariatului',
    'Probe administrate',
    'Constatările comisiei',
    'Semnături',
  ]),
  t('referat-cercetare', 'munca', 'Referat de cercetare disciplinară', 'Concluziile comisiei și propunerea de sancționare.', [
    'Sesizarea și numirea comisiei',
    'Fapta cercetată',
    'Desfășurarea cercetării',
    'Probe și apărările salariatului',
    'Analiza criteriilor din art. 250 Codul muncii',
    'Concluzii',
    'Propunerea de sancționare',
    'Semnături',
  ]),
  t('acord-incetare-cim', 'munca', 'Acord de încetare a contractului de muncă', 'Încetare prin consimțământul părților (art. 55 lit. b).', [
    'Părțile și contractul de muncă',
    'Acordul de încetare și data încetării',
    'Drepturi salariale și compensații',
    'Concediul de odihnă neefectuat',
    'Predarea bunurilor și a documentelor',
    'Obligații care supraviețuiesc încetării',
    'Semnături',
  ]),
  t('clauza-neconcurenta', 'munca', 'Clauză de neconcurență', 'Act adițional cu clauza din art. 21 Codul muncii.', [
    'Părțile și contractul de muncă',
    'Activitățile interzise',
    'Terții în favoarea cărora se interzice prestarea activității',
    'Aria geografică',
    'Durata efectelor clauzei',
    'Indemnizația de neconcurență lunară',
    'Răspunderea salariatului',
    'Semnături',
  ]),
  t('clauza-confidentialitate-munca', 'munca', 'Clauză de confidențialitate (salariat)', 'Act adițional cu clauza din art. 26 Codul muncii.', [
    'Părțile și contractul de muncă',
    'Informațiile confidențiale',
    'Obligațiile salariatului',
    'Durata obligației',
    'Excepții',
    'Răspunderea pentru încălcare',
    'Semnături',
  ]),
  t('clauza-mobilitate', 'munca', 'Clauză de mobilitate', 'Act adițional cu clauza din art. 25 Codul muncii.', [
    'Părțile și contractul de muncă',
    'Lipsa unui loc de muncă stabil',
    'Aria de desfășurare a activității',
    'Prestații suplimentare în bani sau în natură',
    'Decontarea cheltuielilor',
    'Semnături',
  ]),
  t('clauza-formare', 'munca', 'Clauză de formare profesională', 'Act adițional privind formarea plătită de angajator.', [
    'Părțile și contractul de muncă',
    'Programul de formare, durata și costul',
    'Drepturile salariatului pe durata formării',
    'Perioada în care salariatul nu poate avea inițiativa încetării',
    'Restituirea cheltuielilor de formare',
    'Semnături',
  ]),
  t('ccm', 'munca', 'Contract colectiv de muncă la nivel de unitate', 'Negociat între angajator și reprezentanții salariaților.', [
    'Părțile și reprezentarea lor',
    'Dispoziții generale, durată și aplicare',
    'Timpul de muncă și timpul de odihnă',
    'Salarizare și alte drepturi bănești',
    'Condiții de muncă, sănătate și securitate',
    'Formare profesională',
    'Încheierea, modificarea și încetarea contractelor individuale',
    'Drepturile reprezentanților salariaților',
    'Soluționarea conflictelor',
    'Dispoziții finale',
    'Semnături',
  ]),

  // ── Societar / corporate ──────────────────────────────────────────────
  t('hotarare-aga', 'corporate', 'Hotărâre AGA', 'Hotărârea adunării generale a asociaților sau acționarilor.', [
    'Societatea și datele de identificare',
    'Convocarea și cvorumul',
    'Ordinea de zi',
    'Dezbateri',
    'Hotărâri adoptate și rezultatul votului',
    'Împuternicirea pentru formalitățile la ONRC',
    'Semnături',
  ], { top: true }),
  t('decizie-asociat-unic', 'corporate', 'Decizia asociatului unic', 'Echivalentul hotărârii AGA în SRL-ul cu asociat unic.', [
    'Societatea și datele de identificare',
    'Asociatul unic',
    'Preambul',
    'Decizii',
    'Împuternicirea pentru formalitățile la ONRC',
    'Semnătura',
  ], { top: true }),
  t('act-constitutiv', 'corporate', 'Act constitutiv SRL', 'Actul de înființare al societății (Legea 31/1990).', [
    'Asociații',
    'Denumirea, forma juridică, sediul și durata',
    'Obiectul de activitate',
    'Capitalul social și părțile sociale',
    'Adunarea generală a asociaților',
    'Administrarea societății',
    'Controlul gestiunii',
    'Exercițiul financiar, profitul și pierderile',
    'Cesiunea părților sociale',
    'Dizolvarea și lichidarea',
    'Dispoziții finale',
    'Semnături',
  ]),
  t('act-aditional-constitutiv', 'corporate', 'Act adițional la actul constitutiv', 'Modifică actul constitutiv în baza unei hotărâri AGA.', [
    'Societatea și hotărârea în temeiul căreia se modifică',
    'Articolele modificate',
    'Noua formulare a articolelor',
    'Menținerea celorlalte prevederi',
    'Semnături',
  ]),
  t('act-constitutiv-actualizat', 'corporate', 'Act constitutiv actualizat', 'Textul la zi, cu toate modificările încorporate.', [
    'Asociații',
    'Denumirea, forma juridică, sediul și durata',
    'Obiectul de activitate',
    'Capitalul social și părțile sociale',
    'Adunarea generală a asociaților',
    'Administrarea societății',
    'Exercițiul financiar, profitul și pierderile',
    'Dizolvarea și lichidarea',
    'Mențiune privind actele modificatoare încorporate',
    'Semnături',
  ]),
  t('cesiune-parti-sociale', 'corporate', 'Contract de cesiune de părți sociale', 'Transmiterea părților sociale către un asociat sau un terț.', contract(
    'Părțile sociale cesionate',
    'Prețul cesiunii și plata',
    'Aprobarea adunării generale',
    'Declarații și garanții ale cedentului',
    'Transferul dreptului de proprietate',
    'Înregistrarea la registrul comerțului',
  )),
  t('declaratie-beneficiar-real', 'corporate', 'Declarație privind beneficiarul real', 'Declarația cerută de Legea 129/2019, pentru ONRC.', [
    'Declarantul și calitatea sa',
    'Societatea',
    'Beneficiarii reali și datele de identificare',
    'Modalitatea de exercitare a controlului',
    'Declarația pe propria răspundere',
    'Data și semnătura',
  ]),
  t('declaratie-proprie-raspundere', 'corporate', 'Declarație pe propria răspundere (ONRC)', 'Îndeplinirea condițiilor pentru calitatea de asociat sau administrator.', [
    'Declarantul',
    'Societatea și calitatea deținută',
    'Îndeplinirea condițiilor legale',
    'Lipsa incompatibilităților',
    'Mențiunea privind falsul în declarații',
    'Data și semnătura',
  ]),
  t('specimen-semnatura', 'corporate', 'Specimen de semnătură', 'Specimenul de semnătură al reprezentantului societății.', [
    'Reprezentantul și datele de identificare',
    'Societatea și calitatea deținută',
    'Specimenul de semnătură',
    'Data și certificarea',
  ]),
  t('procura-speciala', 'corporate', 'Procură / mandat special', 'Împuternicire pentru operațiuni determinate.', [
    'Mandantul',
    'Mandatarul',
    'Obiectul mandatului',
    'Puterile conferite',
    'Limitele mandatului',
    'Durata și revocarea',
    'Data și semnătura',
  ]),
  t('documentatie-infiintare', 'corporate', 'Documentație de înființare SRL', 'Pachetul de acte pentru înmatricularea la ONRC.', [
    'Lista documentelor din dosar',
    'Rezervarea denumirii',
    'Act constitutiv',
    'Declarații pe propria răspundere',
    'Dovada sediului social',
    'Declarația privind beneficiarul real',
    'Specimene de semnătură',
    'Împuternicirea pentru depunere',
  ]),
  t('majorare-capital', 'corporate', 'Hotărâre de majorare a capitalului social', 'Majorare prin aport nou, încorporare de rezerve sau conversie.', [
    'Societatea și datele de identificare',
    'Convocarea și cvorumul',
    'Capitalul social actual',
    'Sursa și valoarea majorării',
    'Noua structură a capitalului',
    'Modificarea actului constitutiv',
    'Împuternicirea pentru formalitățile la ONRC',
    'Semnături',
  ]),
  t('schimbare-sediu', 'corporate', 'Hotărâre de schimbare a sediului social', 'Mutarea sediului și actualizarea actului constitutiv.', [
    'Societatea și datele de identificare',
    'Convocarea și cvorumul',
    'Sediul actual și noul sediu',
    'Dovada dreptului de folosință',
    'Modificarea actului constitutiv',
    'Împuternicirea pentru formalitățile la ONRC',
    'Semnături',
  ]),
  t('dizolvare-lichidare', 'corporate', 'Hotărâre de dizolvare și lichidare', 'Dizolvarea voluntară a societății (art. 235 Legea 31/1990).', [
    'Societatea și datele de identificare',
    'Convocarea și cvorumul',
    'Hotărârea de dizolvare',
    'Situația activului și a pasivului',
    'Stingerea datoriilor și repartizarea activului',
    'Radierea societății',
    'Împuternicirea pentru formalitățile la ONRC',
    'Semnături',
  ]),
  t('spa', 'corporate', 'Contract de vânzare de acțiuni / părți sociale (SPA)', 'Contractul principal al unei tranzacții M&A.', [
    'Părțile',
    'Definiții și interpretare',
    'Obiectul vânzării',
    'Prețul și mecanismul de ajustare',
    'Condiții suspensive',
    'Perioada dintre semnare și finalizare',
    'Finalizarea tranzacției',
    'Declarații și garanții ale vânzătorului',
    'Despăgubiri și limitarea răspunderii',
    'Neconcurență și nesolicitare',
    'Confidențialitate',
    'Legea aplicabilă și soluționarea litigiilor',
    'Semnături',
  ]),
  t('raport-due-diligence', 'corporate', 'Raport de due diligence juridic', 'Constatările analizei juridice asupra unei societăți-țintă.', [
    'Sumar executiv și riscuri majore',
    'Obiectul, limitele și baza analizei',
    'Aspecte societare',
    'Contracte comerciale',
    'Active și proprietăți imobiliare',
    'Finanțări și garanții',
    'Dreptul muncii',
    'Proprietate intelectuală și IT',
    'Protecția datelor și conformitate',
    'Litigii',
    'Autorizații și reglementare',
    'Recomandări',
  ]),
  t('disclosure-letter', 'corporate', 'Disclosure letter', 'Dezvăluirile vânzătorului față de garanțiile din SPA.', [
    'Părțile și contractul de referință',
    'Scopul și efectul dezvăluirilor',
    'Dezvăluiri generale',
    'Dezvăluiri specifice, pe fiecare garanție',
    'Documente anexate',
    'Semnături',
  ]),

  // ── Compliance și GDPR ────────────────────────────────────────────────
  t('politica-confidentialitate', 'gdpr', 'Politică de confidențialitate', 'Informarea persoanelor vizate (art. 13–14 GDPR).', [
    'Cine suntem: operatorul și datele de contact',
    'Ce date prelucrăm',
    'Scopurile și temeiurile prelucrării',
    'Cui transmitem datele',
    'Transferuri în afara SEE',
    'Cât timp păstrăm datele',
    'Drepturile dumneavoastră',
    'Securitatea datelor',
    'Modificări ale politicii',
    'Contact și plângeri',
  ]),
  t('politica-cookies', 'gdpr', 'Politică de cookies', 'Tipurile de cookie-uri folosite și gestionarea consimțământului.', [
    'Ce sunt cookie-urile',
    'Cookie-urile pe care le folosim',
    'Scopul fiecărei categorii',
    'Cookie-uri ale terților',
    'Durata de stocare',
    'Gestionarea consimțământului și a preferințelor',
    'Modificări ale politicii',
    'Contact',
  ]),
  t('dpa', 'gdpr', 'Acord de prelucrare a datelor (DPA)', 'Contract operator–persoană împuternicită (art. 28 GDPR).', [
    'Părțile',
    'Obiectul, natura și durata prelucrării',
    'Categorii de date și de persoane vizate',
    'Instrucțiunile operatorului',
    'Confidențialitate',
    'Măsuri tehnice și organizatorice',
    'Subîmputerniciți',
    'Asistență pentru drepturile persoanelor vizate',
    'Notificarea încălcărilor de securitate',
    'Audit',
    'Ștergerea sau restituirea datelor',
    'Răspundere',
    'Semnături',
  ]),
  t('acord-transfer', 'gdpr', 'Acord de transfer de date', 'Transfer către o țară terță, pe baza clauzelor contractuale standard.', [
    'Părțile: exportatorul și importatorul de date',
    'Descrierea transferului',
    'Clauzele contractuale standard aplicabile',
    'Evaluarea impactului transferului',
    'Măsuri suplimentare',
    'Drepturile persoanelor vizate',
    'Răspundere',
    'Legea aplicabilă și instanța competentă',
    'Semnături',
  ]),
  t('registru-prelucrari', 'gdpr', 'Registrul activităților de prelucrare', 'Evidența cerută de art. 30 GDPR.', [
    'Operatorul și responsabilul cu protecția datelor',
    'Activitatea de prelucrare',
    'Scopul prelucrării',
    'Categorii de persoane vizate și de date',
    'Temeiul juridic',
    'Destinatari',
    'Transferuri către țări terțe',
    'Termene de ștergere',
    'Măsuri de securitate',
  ], { note: 'Prezintă activitățile de prelucrare sub formă de tabel, cu câte un rând pentru fiecare activitate.' }),
  t('dpia', 'gdpr', 'Evaluarea impactului asupra protecției datelor (DPIA)', 'Evaluarea cerută de art. 35 GDPR pentru prelucrări cu risc ridicat.', [
    'Descrierea prelucrării',
    'Necesitatea și proporționalitatea',
    'Consultarea părților interesate',
    'Riscuri pentru drepturile și libertățile persoanelor',
    'Măsuri de reducere a riscurilor',
    'Risc rezidual',
    'Avizul responsabilului cu protecția datelor',
    'Concluzii și aprobare',
  ]),
  t('termeni-conditii', 'gdpr', 'Termeni și condiții (site / e-commerce)', 'Condițiile de utilizare și de vânzare online (OUG 34/2014).', [
    'Informații despre comerciant',
    'Definiții',
    'Contul de utilizator',
    'Plasarea comenzii și încheierea contractului',
    'Prețuri și plată',
    'Livrare',
    'Dreptul de retragere',
    'Garanții și conformitatea produselor',
    'Răspundere',
    'Proprietate intelectuală',
    'Reclamații, SAL și SOL',
    'Legea aplicabilă',
  ]),
  t('whistleblowing', 'gdpr', 'Politică de whistleblowing', 'Procedura de raportare internă cerută de Legea 361/2022.', policy(
    'Cine poate raporta și ce se poate raporta',
    'Canalele interne de raportare',
    'Persoana desemnată să primească raportările',
    'Procedura și termenele de soluționare',
    'Confidențialitate și protecția datelor',
    'Interzicerea represaliilor',
    'Raportarea externă și divulgarea publică',
    'Evidența raportărilor',
  ), { note: 'Respectă termenele și obligațiile din Legea nr. 361/2022 privind protecția avertizorilor în interes public.' }),
  t('anticoruptie', 'gdpr', 'Politică anticorupție', 'Reguli interne privind mita, cadourile și relația cu terții.', policy(
    'Interzicerea mitei și a plăților de facilitare',
    'Cadouri, ospitalitate și sponsorizări',
    'Relația cu funcționarii publici',
    'Verificarea partenerilor și a intermediarilor',
    'Evidențe contabile și controale',
    'Raportarea suspiciunilor',
    'Sancțiuni',
  )),
  t('conflict-interese', 'gdpr', 'Politică privind conflictul de interese', 'Identificarea, declararea și gestionarea conflictelor de interese.', policy(
    'Ce constituie conflict de interese',
    'Obligația de declarare',
    'Evaluarea și gestionarea conflictelor',
    'Abținerea de la decizie',
    'Registrul declarațiilor',
    'Sancțiuni',
  )),

  // ── Imobiliare ────────────────────────────────────────────────────────
  t('antecontract-imobil', 'imobiliare', 'Antecontract de vânzare imobil', 'Promisiune bilaterală privind un imobil.', contract(
    'Imobilul și situația de carte funciară',
    'Prețul, avansul și graficul de plăți',
    'Termenul de încheiere a contractului în formă autentică',
    'Declarații ale promitentului-vânzător',
    'Obligațiile promitentului-cumpărător',
    'Notarea promisiunii în cartea funciară',
    'Clauza penală și pactul comisoriu',
  )),
  t('vanzare-imobil', 'imobiliare', 'Contract de vânzare imobil', 'Proiect pentru autentificare la notarul public.', contract(
    'Imobilul și situația de carte funciară',
    'Modul de dobândire de către vânzător',
    'Prețul și modalitatea de plată',
    'Declarații ale vânzătorului',
    'Sarcini, impozite și certificat energetic',
    'Predarea imobilului și transferul proprietății',
    'Garanția contra evicțiunii și a viciilor',
    'Înscrierea în cartea funciară',
  ), { note: NOTE_AUTHENTIC }),
  t('inchiriere-comercial', 'imobiliare', 'Contract de închiriere spațiu comercial', 'Cu anexe: fit-out, service charge și garanție.', [
    'Părțile contractante',
    'Spațiul închiriat și destinația lui',
    'Durata și opțiunea de prelungire',
    'Chiria, indexarea și modalitatea de plată',
    'Taxa de servicii (service charge) și utilități',
    'Garanția',
    'Predarea spațiului și lucrările de amenajare (fit-out)',
    'Obligațiile locatorului',
    'Obligațiile locatarului',
    'Asigurări',
    'Subînchiriere și cesiune',
    'Încetarea contractului și restituirea spațiului',
    'Legea aplicabilă și soluționarea litigiilor',
    'Semnături',
    'Anexa 1 — Planul spațiului',
    'Anexa 2 — Specificații fit-out',
    'Anexa 3 — Calculul service charge',
    'Anexa 4 — Modelul garanției',
  ]),
  t('dezmembrare', 'imobiliare', 'Act de dezmembrare', 'Împărțirea unui imobil în două sau mai multe loturi.', [
    'Proprietarul',
    'Imobilul supus dezmembrării',
    'Documentația cadastrală și referatul de admitere',
    'Loturile rezultate',
    'Sarcini și notări care se transmit',
    'Înscrierea în cartea funciară',
    'Semnături',
  ], { note: NOTE_AUTHENTIC }),
  t('alipire', 'imobiliare', 'Act de alipire', 'Unirea a două sau mai multe imobile alăturate.', [
    'Proprietarul',
    'Imobilele supuse alipirii',
    'Documentația cadastrală și referatul de admitere',
    'Imobilul rezultat',
    'Sarcini și notări care se transmit',
    'Înscrierea în cartea funciară',
    'Semnături',
  ], { note: NOTE_AUTHENTIC }),
  t('servitute', 'imobiliare', 'Contract de constituire a unei servituți', 'Servitute de trecere sau de utilități asupra fondului aservit.', contract(
    'Fondul dominant și fondul aservit',
    'Conținutul și traseul servituții',
    'Durata',
    'Prețul sau caracterul gratuit',
    'Obligațiile proprietarului fondului aservit',
    'Obligațiile proprietarului fondului dominant',
    'Înscrierea în cartea funciară',
  )),
  t('superficie', 'imobiliare', 'Contract de superficie', 'Dreptul de a avea o construcție pe terenul altuia.', contract(
    'Terenul',
    'Construcția edificată sau care se va edifica',
    'Durata superficiei',
    'Prestația datorată proprietarului terenului',
    'Obligațiile superficiarului',
    'Obligațiile proprietarului terenului',
    'Soarta construcției la încetare',
    'Înscrierea în cartea funciară',
  )),
  t('uzufruct', 'imobiliare', 'Contract de constituire a uzufructului', 'Dreptul de a folosi bunul și de a-i culege fructele.', contract(
    'Bunul asupra căruia se constituie uzufructul',
    'Durata uzufructului',
    'Prețul sau caracterul gratuit',
    'Inventarul și starea bunului',
    'Drepturile și obligațiile uzufructuarului',
    'Drepturile și obligațiile nudului proprietar',
    'Înscrierea în cartea funciară',
  )),
  t('drept-folosinta', 'imobiliare', 'Contract privind dreptul de folosință', 'Folosința unui imobil pentru sediu, utilități sau acces.', contract(
    'Imobilul și suprafața vizată',
    'Scopul folosinței',
    'Durata',
    'Prețul sau caracterul gratuit',
    'Obligațiile proprietarului',
    'Obligațiile titularului dreptului de folosință',
  )),
  t('antrepriza-constructii', 'imobiliare', 'Contract de antrepriză pentru construcții', 'Execuție de lucrări, pe structura condițiilor FIDIC.', [
    'Acordul contractual și părțile',
    'Definiții și interpretare',
    'Beneficiarul',
    'Inginerul / dirigintele de șantier',
    'Antreprenorul',
    'Proiectare',
    'Personal, utilaje, materiale și execuție',
    'Începerea, întârzieri și suspendarea lucrărilor',
    'Teste la terminare și recepția lucrărilor',
    'Perioada de garanție și remedierea defecțiunilor',
    'Măsurare, evaluare și modificări',
    'Prețul contractului și plățile',
    'Rezilierea și suspendarea de către părți',
    'Riscuri, asigurări și forța majoră',
    'Revendicări, dispute și arbitraj',
    'Semnături',
  ], { note: 'Urmează logica Condițiilor Generale FIDIC (Cartea Roșie), adaptată dreptului român și Legii nr. 10/1995 privind calitatea în construcții.' }),
  t('due-diligence-imobiliar', 'imobiliare', 'Raport de due diligence imobiliar', 'Analiza juridică a unui imobil înainte de tranzacție.', [
    'Sumar executiv și riscuri majore',
    'Obiectul, limitele și baza analizei',
    'Identificarea imobilului',
    'Istoricul dreptului de proprietate',
    'Situația de carte funciară și cadastru',
    'Sarcini, ipoteci și litigii',
    'Urbanism și autorizații de construire',
    'Contracte de închiriere și de utilități',
    'Aspecte fiscale și de mediu',
    'Recomandări',
  ]),
  t('nota-titlu', 'imobiliare', 'Notă de titlu', 'Verificarea pe scurt a lanțului de proprietate.', [
    'Imobilul analizat',
    'Documente verificate',
    'Lanțul transmisiunilor',
    'Situația de carte funciară',
    'Riscuri identificate',
    'Concluzie asupra titlului',
  ]),
  t('administrare-mentenanta', 'imobiliare', 'Contract de administrare și mentenanță', 'Administrarea și întreținerea unei clădiri.', contract(
    'Imobilul administrat',
    'Serviciile de administrare',
    'Serviciile de mentenanță tehnică',
    'Niveluri de serviciu și raportare',
    'Durata contractului',
    'Prețul și modalitatea de plată',
    'Bugetul de cheltuieli și refacturarea',
    'Obligațiile administratorului',
    'Obligațiile proprietarului',
    'Asigurări',
  )),
];

// Folded for search: lower-case, diacritics stripped — a lawyer types
// "intampinare", the label says "Întâmpinare", and both have to meet.
export const foldText = (v) => String(v || '')
  .normalize('NFD').replace(/[̀-ͯ]/g, '')
  .toLowerCase();

// Templates matching a category chip and a typed query. Every word of the query
// has to be somewhere in the label, the blurb or the section names, so "decizie
// concediere" narrows rather than widens.
export function searchTemplates(query, category = 'all') {
  const words = foldText(query).split(/\s+/).filter(Boolean);
  return DOC_TEMPLATES.filter((tpl) => {
    if (category === 'top' ? !tpl.top : (category !== 'all' && tpl.category !== category)) return false;
    if (!words.length) return true;
    const hay = foldText(`${tpl.label} ${tpl.blurb} ${tpl.outline.join(' ')}`);
    return words.every((w) => hay.includes(w));
  });
}

export function templateById(id) {
  return DOC_TEMPLATES.find((t) => t.id === id) || null;
}

// One blank shape for every generated document: square brackets around a short
// description of what the person has to supply. Anything else — underscores,
// dotted rules, curly braces, "TBD" — either escapes the Complete-data panel's
// scan or reads inconsistently next to the blanks that don't.
const PLACEHOLDER_RULE_RO =
  'Nu inventa date. Scrie fiecare spațiu de completat între paranteze drepte DUBLE, iar în interior pune '
  + 'NUMELE CÂMPULUI din această listă: legalName, aka, nationalId, dateOfBirth, nationality, idDocument, '
  + 'idSeries, idNumber, idIssuer, idIssuedAt, idType, placeOfBirth, taxId, regNo, legalForm, representative, '
  + 'repCapacity, iban, bank, address, addressStreet, addressNumber, '
  + 'addressBlock, addressStair, addressFloor, addressApartment, addressLocality, addressCounty, city, county, country, email, phone. '
  + 'Pune înaintea numelui partea implicată atunci când sunt mai multe — [[vanzator.legalName]], '
  + '[[cumparator.nationalId]] — și folosește numele simplu când este una singură: [[legalName]]. '
  + 'DocVex ține câte o fișă pentru fiecare parte, așa că un spațiu numit astfel se completează dintr-un clic. '
  + 'GREȘIT: domiciliat în [localitatea], str. [...], nr. [...], bl. [...], CNP [...]. '
  + 'CORECT: domiciliat în [[vanzator.addressLocality]], str. [[vanzator.addressStreet]], '
  + 'nr. [[vanzator.addressNumber]], bl. [[vanzator.addressBlock]], CNP [[vanzator.nationalId]]. '
  + 'Câte un spațiu separat pentru fiecare informație. Pentru ce nu se află în listă (un preț, un termen, '
  + 'autoritatea emitentă) folosește tot paranteze duble, cu o descriere scurtă: [[prețul convenit în lei]]. '
  + 'Niciodată „[...]”, „[…]”, paranteze goale, liniuțe (____), puncte (....), {acolade} sau <paranteze unghiulare>. '
  + 'GEN: păstrează formulele care acoperă ambele variante — „Domnul/Doamna”, „domiciliat(ă)”, '
  + '„identificat(ă)”. DocVex le rezolvă din fișa părții la completare, deci nu alege tu genul.';

// The opening instruction for a picked template.
//
// Placeholders, not invented facts: the drafter does not know the parties yet,
// so it is told to leave every unknown as a bracketed blank. Those blanks are
// exactly what the Doc Viewer's "Complete data" panel later finds and fills, so
// the two features meet in the middle — and the panel finds them BY SHAPE
// (`matchFields` scans for square brackets), which is why the rule below spells
// out one blank style and forbids the rest. Keep it in step with
// PLACEHOLDER_RULE in supabase/functions/project-ai/index.ts.
export function templatePrompt(template) {
  if (!template) return '';
  return [
    // Named after a colon rather than "Redactează un …": the labels are of
    // every gender and number, and an article that fits one is wrong for most.
    `Redactează următorul document, complet, în limba română: ${template.label}.`,
    '',
    'Structurează documentul exact pe aceste secțiuni, în această ordine:',
    ...template.outline.map((s, i) => `${i + 1}. ${s}`),
    '',
    'Reguli:',
    '- Scrie textul integral, în limbaj juridic corect și uzual.',
    `- ${PLACEHOLDER_RULE_RO}`,
    '- Folosește exact aceleași denumiri de secțiuni de mai sus ca titluri.',
    ...(template.note ? [`- ${template.note}`] : []),
  ].join('\n');
}

// A free-text answer to "what do you want to make?". Kept in the same shape as
// a template prompt so the advisor is entered the same way either way.
export function customPrompt(text) {
  const wanted = String(text || '').trim();
  if (!wanted) return '';
  return [
    wanted,
    '',
    PLACEHOLDER_RULE_RO,
  ].join('\n');
}
